export const REQUEST_SOURCES = 'REQUEST_SOURCES';
export const RECEIVE_SOURCES = 'RECEIVE_SOURCES';
export const UPDATE_SOURCE_LIST_ID = 'UPDATE_SOURCE_LIST_ID';
export const UPDATE_SOURCE_URL = 'UPDATE_SOURCE_URL';
export const REQUEST_ARTICLES = 'REQUEST_ARTICLES';
export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';
